apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:60040
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:60042
    editable: false

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://localhost:60044
    editable: false

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://localhost:60032
    jsonData:
      defaultDatabase: lnk_analytics
    editable: false
